package ttfm:plugin;

// 必須インターフェース
interface core {
    name: func() -> string;
    version: func() -> string;
}

// 省略可能インターフェース

interface indexing {
    enum value-type { text, big-int, boolean, double }

    variant tag-value {
        text(string),
        big-int(s64),
        boolean(bool),
        double(f64),
        empty,
    }

    get-value-type: func() -> value-type;
    tag-file: func(path: string) -> list<tag-value>;
}

interface query {
    normalize-label: func(label: string) -> option<string>;
    expand: func(tag-type: string, label: string) -> option<string>;
    expand-projection: func(tag-type: string) -> option<string>;
}

interface display {
    record display-format {
        id: string,
        label: string,
    }

    default-format: func() -> option<display-format>;
    formats: func() -> list<display-format>;
    show: func(value: string, format-id: string) -> string;
}

// プラグイン作者向け
world plugin {
    export core;
    export indexing;
    export query;
    export display;
}
